apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-customer.fullname" . }}-web-customer
  labels:
    app: web-customer
  {{- include "web-customer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webCustomer.type }}
  selector:
    app: web-customer
  {{- include "web-customer.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webCustomer.ports | toYaml | nindent 2 -}}