apiVersion: v1
kind: Service
metadata:
  name: {{ include "web-admin.fullname" . }}-web-admin
  labels:
    app: web-admin
  {{- include "web-admin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webAdmin.type }}
  selector:
    app: web-admin
  {{- include "web-admin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webAdmin.ports | toYaml | nindent 2 -}}