apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-customer
#  namespace: default
spec:
  selector:
    matchLabels:
      app: web-customer
  replicas: 1
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
 
  template:
    metadata:
      labels:
        app: web-customer
    spec:
      containers:
      - name: web-customer
        image: web-customer:1.1
        imagePullPolicy: Never
#        resources:
#          limits:
#            memory: "1024Mi"
#            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_DATABASE 
          value: mya2billing
        - name: MYSQL_PASSWORD
          value: a2billing
        - name: MYSQL_ROOT_PASSWORD 
          value: "123456"
        - name: MYSQL_USER
          value: a2billinguser
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: PMA_HOST
          value: db-server
        - name: PMA_PORT
          value: "3306"

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-customer
  name: web-customer
#  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: web-customer
  selector:
    app: web-customer
