apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-server
#  namespace: default
spec:
  selector:
    matchLabels:
      app: db-server
  replicas: 1
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
 
  template:
    metadata:
      labels:
        app: db-server
    spec:
      containers:
      - name: db-server
        image: mysql-test:1.1
        imagePullPolicy: Never
#        resources:
#          limits:
#            memory: "1024Mi"
#            cpu: "1000m"
        ports:
        - containerPort: 3306
        env:
#        - name: AUTH
#          value: "yes"
        - name: MYSQL_DATABASE 
          value: mya2billing
        - name: MYSQL_PASSWORD
          value: a2billing
        - name: MYSQL_ROOT_PASSWORD 
          value: "123456"
        - name: MYSQL_USER
          value: a2billinguser
        - name: MYSQL_ROOT_HOST
          value: '%'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-server
  name: db-server
#  namespace: default
spec:
  type: ClusterIP 
  ports:
    - port: 3306
      targetPort: 3306
      name: db-server
  selector:
    app: db-server
