apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
#  namespace: default
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  replicas: 1
  strategy:
     type: RollingUpdate
     rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
 
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: "phpmyadmin/phpmyadmin:latest"
        imagePullPolicy: Always
#        resources:
#          limits:
#            memory: "1024Mi"
#            cpu: "1000m"
        ports:
        - containerPort: 80
        env:
#        - name: AUTH
#          value: "yes"
        - name: MYSQL_DATABASE 
          value: mya2billing
        - name: MYSQL_PASSWORD
          value: a2billing
        - name: MYSQL_ROOT_PASSWORD 
          value: "123456"
        - name: MYSQL_USER
          value: a2billinguser
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: PMA_HOST
          value: db-server
        - name: PMA_PORT
          value: "3306"
        

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
#  namespace: default
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      name: phpmyadmin
  selector:
    app: phpmyadmin
