apiVersion: v1
kind: Service
metadata:
  name: {{ include "db-server.fullname" . }}-db-server
  labels:
    app: db-server
  {{- include "db-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dbServer.type }}
  selector:
    app: db-server
  {{- include "db-server.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.dbServer.ports | toYaml | nindent 2 -}}