apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db-server.fullname" . }}-db-server
  labels:
  {{- include "db-server.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.dbServer.replicas }}
  selector:
    matchLabels:
      app: db-server
    {{- include "db-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: db-server
      {{- include "db-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: mya2billing
        - name: MYSQL_PASSWORD
          value: a2billing
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_USER
          value: a2billinguser
        - name: MYSQL_ROOT_HOST
          value: %
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ .Values.kubernetesClusterDomain }}
        image: {{ .Values.dbServer.dbServer.image.repository }}:{{ .Values.dbServer.dbServer.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: Never
        name: db-server
        ports:
        - containerPort: 3306
        resources: {}