apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nginx.fullname" . }}-global-ingress
  labels:
  {{- include "nginx.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: cluster
    http:
      paths:
      - backend:
          service:
            name: sip-server
            port:
              number: 5060
        path: /sip
        pathType: ImplementationSpecific
      - backend:
          service:
            name: web-admin
            port:
              number: 80
        path: /admin
        pathType: ImplementationSpecific
      - backend:
          service:
            name: web-customer
            port:
              number: 80
        path: /customer
        pathType: ImplementationSpecific
      - backend:
          service:
            name: phpmyadmin
            port:
              number: 80
        path: /phpmyadmin
        pathType: ImplementationSpecific