apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpmyadmin.fullname" . }}-phpmyadmin
  labels:
    app: phpmyadmin
  {{- include "phpmyadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.phpmyadmin.type }}
  selector:
    app: phpmyadmin
  {{- include "phpmyadmin.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.phpmyadmin.ports | toYaml | nindent 2 -}}